#!/usr/bin/env bash

# Ollama list returns 1 if there is no server
ollama list > /dev/null 2>&1
ollama_status="$?"


update_models() {
    local models
    readarray < <(ollama ls | awk 'NR >= 2 {print $1}') models

    echo -e "Updating Ollama models...\n"
    for model in "${models[@]}"; do
        echo "Updating model $model..."
        ollama pull "$model"
        echo 
    done
    echo -e "\nFinished updating models."

    return 0
}

if (( ollama_status == 0 )); then
    update_models
else
    echo "Ollama is not running. No models were updated." 2>&1
    exit 1
fi
